### ISSUE TITLE
FUSE filesystems

### ISSUE THREAD

**Issue by piranna** [MarcoPon/SeqBox#4]
When reading the project description the only though I had in my mind was about use SeqBox as a filesystem format focused on reliability and data recovery (I like this kind of things :-) ), later I see that you had it also as a posible use case so hope to see it soon! :-D

**Comment by MarcoPon** [comment]
Yes I plan to do something like that! Would be interesting even just to play with, probably! :)

**Comment by piranna** [comment]
Definitely :-) Main problem would be access speed due to non-aligned data and lower data density, but you can't have everything :-P
