### ISSUE TITLE
sha256 is slow

### ISSUE THREAD

**Issue by ThomasWaldmann** [MarcoPon/SeqBox#5]
jfyi: sha256 < sha512(-256) < blake2b for 64bit cpus.

**Comment by MarcoPon** [comment]
Yes of course. I initially wanted to use blake2b/s, then I saw that it was supported only by the latest version of Python, so I opted for some more generally available. Anyway, just the fact that it's written in Python means that performance wasn't really the main point of the tool - the whole code is surely not speed optimized, I tried to lean on the clarity/simplicity side if/where possible.  Other hash types can easily be added, and probably will, btw.

**Comment by ThomasWaldmann** [comment]
OK.

If blake2b is too much of a hassle, you can always use sha512 and only use 256bits of the result (usually called sha512-256 then).

**Comment by MarcoPon** [comment]
Yes that would be faster on 64bit CPUs (and slower on 32bit ones). I'll keep that in mind and may add it, but probably as time passes it would simpler to just add blake2*. But again, it's not really a great priority at the moment.
